# Generated by Django 4.2.27 on 2026-01-29 11:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DataMart Production', max_length=100)),
                ('api_key', models.CharField(max_length=255)),
                ('base_url', models.URLField(default='https://datamartbackened.onrender.com/api/developer')),
                ('is_active', models.BooleanField(default=True)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Configuration',
                'verbose_name_plural': 'API Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.CharField(help_text='Data capacity value (e.g. 5 for 5GB)', max_length=20)),
                ('mb', models.CharField(help_text='MB equivalent (e.g. 5000)', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Bundle price in GH₵', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('plan_code', models.CharField(help_text='Internal plan identifier', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Data Bundle',
                'verbose_name_plural': 'Data Bundles',
                'ordering': ['network__name', 'price'],
            },
        ),
        migrations.CreateModel(
            name='DatamartTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('deposit', 'Deposit'), ('refund', 'Refund')], db_column='type', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=20)),
                ('reference', models.CharField(max_length=100)),
                ('gateway', models.CharField(max_length=50)),
                ('api_created_at', models.DateTimeField()),
                ('api_updated_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'DataMart Transaction',
                'verbose_name_plural': 'DataMart Transactions',
                'ordering': ['-api_created_at'],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('YELLO', 'MTN (Yello)'), ('TELECEL', 'Telecel (Vodafone)'), ('AT_PREMIUM', 'AirtelTigo Premium')], help_text='DataMart API network code', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Display name', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Network',
                'verbose_name_plural': 'Networks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_column='recipient_phone', max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('gateway', models.CharField(choices=[('wallet', 'Wallet')], default='wallet', max_length=20)),
                ('payment_method', models.CharField(choices=[('wallet', 'Wallet'), ('mobile_money', 'Mobile Money')], default='wallet', max_length=20)),
                ('paid_from_wallet', models.BooleanField(default=False)),
                ('wallet_balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('wallet_balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('purchase_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('transaction_reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('remaining_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('api_response', models.JSONField(blank=True, null=True)),
                ('geonetechResponse', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('request_method', models.CharField(default='POST', max_length=10)),
                ('request_payload', models.JSONField()),
                ('request_headers', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField()),
                ('status_code', models.PositiveIntegerField()),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Transaction Log',
                'verbose_name_plural': 'Transaction Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_deposited', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_refunded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('purchase', 'Purchase'), ('refund', 'Refund')], db_index=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='kelhub.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='kelhub.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
