# Generated by Django 4.2.27 on 2026-01-29 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kelhub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to='kelhub.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kelhub.databundle'),
        ),
        migrations.AddField(
            model_name='order',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kelhub.network'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datamarttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datamart_transactions', to='kelhub.order'),
        ),
        migrations.AddField(
            model_name='databundle',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='kelhub.network'),
        ),
        migrations.AddIndex(
            model_name='databundle',
            index=models.Index(fields=['network', 'is_active'], name='kelhub_data_network_e4bb4e_idx'),
        ),
        migrations.AddIndex(
            model_name='databundle',
            index=models.Index(fields=['price'], name='kelhub_data_price_72450f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='databundle',
            unique_together={('network', 'capacity')},
        ),
    ]
