# Generated by Django 4.2.27 on 2026-01-27 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kelhub', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databundle',
            options={'ordering': ['price']},
        ),
        migrations.AlterModelOptions(
            name='network',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transactionlog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='databundle',
            name='size',
        ),
        migrations.AddField(
            model_name='databundle',
            name='capacity',
            field=models.CharField(default=django.utils.timezone.now, help_text='e.g., 5GB', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='databundle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='databundle',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='databundle',
            name='mb',
            field=models.CharField(default=django.utils.timezone.now, help_text='MB equivalent', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='network',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='key',
            field=models.CharField(help_text='API network code', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(help_text='Display name', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
