# Generated by Django 4.2.27 on 2026-01-28 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kelhub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='kelhub.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kelhub.databundle'),
        ),
        migrations.AddField(
            model_name='order',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kelhub.network'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='databundle',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='kelhub.network'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['-created_at'], name='kelhub_wall_created_8898bb_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', '-created_at'], name='kelhub_wall_wallet__1cc412_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', '-created_at'], name='kelhub_wall_transac_54cc81_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-created_at'], name='kelhub_orde_created_f610f8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='kelhub_orde_user_id_2abdb7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='kelhub_orde_status_9b00ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='databundle',
            unique_together={('network', 'plan_code')},
        ),
    ]
