# Generated by Django 4.2.27 on 2026-02-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kelhub', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APIConfiguration',
        ),
    ]
