# Generated by Django 4.2.27 on 2026-02-04 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kelhub', '0003_delete_apiconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_log', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
